name: Deploy ke EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Deploy ke EC2
      uses: appleboy/ssh-action@master
      with:
        host: 47.129.159.32
        username: ec2-user
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd ecommerce-uts
          git pull origin main
          pm2 restart all || pm2 start app.js --name ecommerce-app
