name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Copy files to EC2
      uses: appleboy/scp-action@v0.1.4
      with:
        host: 47.129.159.32         # <--- Ganti dengan IP PUBLIC EC2 kamu
        username: ec2-user
        key: ${{ secrets.EC2_SSH_KEY }}  # Ini SSH Private Key yang nanti kita simpan di Secrets
        source: "."
        target: "/home/ec2-user/ecommerce-uts"

    - name: SSH and Restart app
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: 47.129.159.32
        username: ec2-user
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd /home/ec2-user/ecommerce-uts
          npm install
          pm2 restart app.js || pm2 start app.js
          pm2 save
